name: CI
env:
  HUSKY: 0
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install global dependencies
        run: npm ci

      - name: Install smart contract dependencies
        run: cd smart_contracts && npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run smart contract tests
        run: cd smart_contracts && npm test
